version: "3.9"

services:
  web:
    build: .
    container_name: messenger_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/messenger
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: messenger_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
